### ISSUE TITLE
Upgrade wasmtime crate dependency

### ISSUE THREAD

**Issue by viniarck** [viniarck/wasmtime-ex#38]
This is for upgrading wasmtime crate to a recent major stable version

**Comment by joeywang321** [comment]
Have you started already, I'm looking at your commit history and this library is equivalent to a wrapper around wasmtime is it? I don't have experience with wasmtime but I do have experience with wasmer and wasmex, but it was recently updated and I really like wasmtime. i would like to give you a little bit of advice you can use this ([commit specification)](https://www.conventionalcommits.org/en/v1.0.0/) for easy reading, but of course this is just my personal opinion.

**Comment by joeywang321** [comment]
I apologize for being presumptuous, hahaha. This is the only item you didn't use
